<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import StatusBadge from '@/components/StatusBadge.vue'
import { useEmsStore } from '@/stores/ems'
const props = defineProps<{ section: 'strategies' | 'types' | 'issue' | 'schedule' | 'logs' | 'commands' }>()
const store = useEmsStore()
const modal = ref(false)
const editingId = ref('')
const keyword = ref('')
const pageSize = ref(8)
const currentPage = ref(1)
const selectedType = ref('削峰填谷')
const form = reactive({ name: '', type: '削峰填谷', priority: 1, power: '500.0 kW', targetSoc: '75.00%', schedule: '', trigger: '' })
const title = computed(() => ({ strategies: '策略管理', types: '策略类型', issue: '策略下发', schedule: '策略调度计划', logs: '策略执行日志', commands: '实时调度指令' }[props.section]))
const subtitle = computed(() => ({ strategies: '储能运行策略创建、编辑与版本维护', types: '储能调度策略类型与参数项', issue: '策略下发、暂停与停止控制', schedule: '周计划日历调度', logs: '策略执行记录与结果追踪', commands: '实时指令与近期策略调度详情' }[props.section]))
const filterText = (value: string) => value.toLowerCase().includes(keyword.value.trim().toLowerCase())
const filteredStrategies = computed(() => store.strategies.filter((item) => !keyword.value || filterText(`${item.name}${item.type}${item.status}${item.trigger}`)))
const strategyRows = computed(() => filteredStrategies.value.slice((currentPage.value - 1) * pageSize.value, currentPage.value * pageSize.value))
const logRows = computed(() => store.logs.slice((currentPage.value - 1) * pageSize.value, currentPage.value * pageSize.value))
const openStrategy = (strategy?: typeof store.strategies[number]) => { editingId.value = strategy?.id || ''; Object.assign(form, strategy || { name: '新增削峰填谷策略', type: '削峰填谷', priority: 1, power: '500.0 kW', targetSoc: '75.00%', schedule: '每日10:00-15:00、18:00-22:00', trigger: '电价≥0.9元且负荷>2000kW' }); modal.value = true }
const saveStrategy = () => { editingId.value ? store.updateStrategy(editingId.value, form) : store.createStrategy({ ...form }); modal.value = false }
const strategyTypes = [
  { name: '削峰填谷', desc: '谷段充电、峰段放电，按价差与SOC边界闭环执行', target: '降低峰段购电成本，提高谷段消纳能力', chargeWindow: '00:00-07:00、22:00-24:00', dischargeWindow: '10:00-15:00、18:00-22:00', chargePower: 560, dischargePower: 720, socMin: 20, socMax: 90, triggerPrice: 0.9, demandLimit: 0, response: '分钟级', curve: ['充电', '待机', '放电', '待机', '放电', '充电'], risk: '避免连续深度循环导致电池衰减' },
  { name: '需量管理', desc: '基于15分钟平均功率预测，在需量越限前提前放电削峰', target: '降低最大需量电费', chargeWindow: '00:00-06:30', dischargeWindow: '08:30-11:30、14:00-17:30', chargePower: 420, dischargePower: 600, socMin: 35, socMax: 85, triggerPrice: 0.68, demandLimit: 1900, response: '5分钟滚动预测', curve: ['待机', '预充', '削峰放电', '待机', '削峰放电', '补电'], risk: '需保留备电SOC，避免过度削峰' },
  { name: '调频', desc: '按AGC或频率偏差快速充放电，限制SOC与爬坡率', target: '参与辅助服务并提升电网稳定性', chargeWindow: '全天可用', dischargeWindow: '全天可用', chargePower: 300, dischargePower: 300, socMin: 45, socMax: 75, triggerPrice: 0, demandLimit: 0, response: '秒级响应', curve: ['充电脉冲', '放电脉冲', '待机', '放电脉冲', '充电脉冲', '待机'], risk: '高频动作需监控PCS温度与循环次数' },
  { name: '防逆流', desc: '光伏大于负荷时提升充电功率，将并网点反向功率压到阈值内', target: '防止并网点反向送电', chargeWindow: '09:00-16:30', dischargeWindow: '18:00-21:00', chargePower: 480, dischargePower: 260, socMin: 30, socMax: 95, triggerPrice: 0, demandLimit: -30, response: '并网点实时闭环', curve: ['待机', '吸收光伏', '吸收光伏', '限充', '放电补偿', '待机'], risk: 'SOC接近上限时需切换限发策略' },
  { name: '离网备电', desc: '电网异常时切换离网供电，按负荷优先级释放储能', target: '保障关键负荷不断电', chargeWindow: '谷段保持备电SOC', dischargeWindow: '电网异常期间', chargePower: 500, dischargePower: 650, socMin: 50, socMax: 95, triggerPrice: 0, demandLimit: 0, response: '毫秒级切换', curve: ['备电保持', '备电保持', '离网放电', '负荷切除', '恢复并网', '补电'], risk: '需按负荷优先级切除非关键负荷' },
]
const currentType = computed(() => strategyTypes.find((item) => item.name === selectedType.value) || strategyTypes[0])
const weekDays = ['周一','周二','周三','周四','周五','周六','周日']
const weeklyPlans = computed(() => weekDays.map((day, index) => ({ day, plans: store.strategies.map((strategy) => ({ name: strategy.name, time: strategy.schedule || '未配置调度计划', action: index < 5 ? `${strategy.type} · ${strategy.power}` : '周末低负荷待机' })) })))
const recentDispatch = computed(() => store.logs.slice(0, 6).map((log, index) => ({ ...log, strategy: store.strategies[index % store.strategies.length]?.name, command: index % 2 === 0 ? 'PCS有功功率设定' : 'SOC目标调整', response: index % 3 === 0 ? '已响应' : '执行中' })))
</script>
<template>
  <div class="page-grid tob-page">
    <section v-if="section === 'strategies'" class="data-section span-12"><div class="query-bar"><el-input v-model="keyword" clearable placeholder="策略名称 / 类型 / 状态 / 触发条件" /><el-button type="primary">查询</el-button><el-button @click="keyword = ''">重置</el-button><el-button type="primary" plain @click="openStrategy()">新增策略</el-button></div><el-table :data="strategyRows" stripe height="520"><el-table-column label="策略名称" min-width="210"><template #default="{ row }"><strong>{{ row.name }}</strong><small>{{ row.trigger }}</small></template></el-table-column><el-table-column prop="type" label="类型"/><el-table-column prop="priority" label="优先级" width="80"/><el-table-column prop="targetSoc" label="目标SOC"/><el-table-column prop="power" label="功率"/><el-table-column prop="version" label="版本"/><el-table-column label="状态"><template #default="{ row }"><StatusBadge :text="row.status" /></template></el-table-column><el-table-column label="操作" width="150"><template #default="{ row }"><el-button link type="primary" @click="openStrategy(row)">编辑</el-button><el-button link type="danger" @click="store.deleteStrategy(row.id)">删除</el-button></template></el-table-column></el-table><div class="pager-row"><el-pagination v-model:current-page="currentPage" v-model:page-size="pageSize" :total="filteredStrategies.length" layout="total, sizes, prev, pager, next, jumper" /></div></section>
    <section v-else-if="section === 'types'" class="data-section span-12"><div class="date-tools"><el-select v-model="selectedType" style="width: 260px"><el-option v-for="item in strategyTypes" :key="item.name" :label="item.name" :value="item.name" /></el-select><el-tag type="primary">策略属性配置</el-tag></div><div class="strategy-config-layout"><div class="strategy-detail-card"><h3>{{ currentType.name }}</h3><p>{{ currentType.desc }}</p><el-form label-width="110px"><el-form-item label="充电时段"><el-input v-model="currentType.chargeWindow" /></el-form-item><el-form-item label="放电时段"><el-input v-model="currentType.dischargeWindow" /></el-form-item><el-form-item label="充电功率"><el-input v-model.number="currentType.chargePower" type="number"><template #append>kW</template></el-input></el-form-item><el-form-item label="放电功率"><el-input v-model.number="currentType.dischargePower" type="number"><template #append>kW</template></el-input></el-form-item><el-form-item label="SOC下限"><el-input v-model.number="currentType.socMin" type="number"><template #append>%</template></el-input></el-form-item><el-form-item label="SOC上限"><el-input v-model.number="currentType.socMax" type="number"><template #append>%</template></el-input></el-form-item><el-form-item label="触发电价"><el-input v-model.number="currentType.triggerPrice" type="number"><template #append>元/kWh</template></el-input></el-form-item><el-form-item label="需量阈值"><el-input v-model.number="currentType.demandLimit" type="number"><template #append>kW</template></el-input></el-form-item></el-form></div><div class="strategy-detail-card"><h3>日内充放电曲线</h3><div class="strategy-timeline"><span v-for="(step, index) in currentType.curve" :key="step + index" :class="{ charge: step.includes('充'), discharge: step.includes('放') || step.includes('削峰') }"><small>{{ ['00:00','04:00','08:00','12:00','16:00','20:00'][index] }}</small>{{ step }}</span></div><div class="detail-grid"><article><label>策略目标</label><strong>{{ currentType.target }}</strong></article><article><label>响应方式</label><strong>{{ currentType.response }}</strong></article><article><label>风险控制</label><strong>{{ currentType.risk }}</strong></article></div></div></div></section>
    <section v-else-if="section === 'issue'" class="data-section span-12"><div class="query-bar"><el-input v-model="keyword" clearable placeholder="策略名称 / 类型" /><el-button type="primary">查询</el-button><el-button @click="keyword = ''">重置</el-button></div><el-table :data="strategyRows" stripe height="520"><el-table-column prop="name" label="策略"/><el-table-column label="状态"><template #default="{ row }"><StatusBadge :text="row.status" /></template></el-table-column><el-table-column prop="schedule" label="计划"/><el-table-column prop="trigger" label="触发条件"/><el-table-column label="操作" width="210"><template #default="{ row }"><el-button link type="primary" @click="store.issueStrategy(row.id)">下发执行</el-button><el-button link @click="store.updateStrategy(row.id, { status: '暂停' })">暂停</el-button><el-button link type="danger" @click="store.updateStrategy(row.id, { status: '停止' })">停止</el-button></template></el-table-column></el-table><div class="pager-row"><el-pagination v-model:current-page="currentPage" v-model:page-size="pageSize" :total="filteredStrategies.length" layout="total, sizes, prev, pager, next, jumper" /></div></section>
    <section v-else-if="section === 'schedule'" class="data-section span-12"><div class="week-calendar"><article v-for="day in weeklyPlans" :key="day.day" class="day-card"><strong>{{ day.day }}</strong><span v-for="plan in day.plans" :key="plan.name + plan.time" class="plan-chip">{{ plan.time }}<br />{{ plan.name }}<br />{{ plan.action }}</span></article></div></section>
    <section v-else-if="section === 'logs'" class="data-section span-12"><div class="query-bar"><el-input v-model="keyword" clearable placeholder="事件 / 结果" /><el-button type="primary">查询</el-button><el-button @click="keyword = ''">重置</el-button></div><el-table :data="logRows" stripe height="520"><el-table-column prop="time" label="时间"/><el-table-column prop="event" label="事件"/><el-table-column prop="result" label="执行结果"/></el-table><div class="pager-row"><el-pagination v-model:current-page="currentPage" v-model:page-size="pageSize" :total="store.logs.length" layout="total, sizes, prev, pager, next, jumper" /></div></section>
    <section v-else class="data-section span-12"><div class="detail-grid"><article><label>当前指令</label><strong>{{ store.snapshot.mode }}指令</strong></article><article><label>目标功率</label><strong>{{ store.format.kw(Math.abs(store.snapshot.storagePower)) }}</strong></article><article><label>当前SOC</label><strong>{{ store.format.pct(store.snapshot.soc) }}</strong></article><article><label>PCS响应</label><strong>闭环跟随正常，通讯延迟28ms</strong></article><article><label>更新时间</label><strong>{{ store.snapshot.timestamp }}</strong></article></div><h3>近期策略调度详情</h3><el-table :data="recentDispatch" stripe><el-table-column prop="time" label="时间" /><el-table-column prop="strategy" label="策略" /><el-table-column prop="command" label="指令" /><el-table-column prop="result" label="结果" /><el-table-column label="响应"><template #default="{ row }"><StatusBadge :text="row.response" /></template></el-table-column></el-table></section>
    <el-dialog v-model="modal" destroy-on-close class="ems-dialog" title="策略维护" width="680px"><el-form :model="form" label-width="90px"><el-form-item label="策略名称"><el-input v-model="form.name" /></el-form-item><el-form-item label="策略类型"><el-select v-model="form.type"><el-option v-for="item in strategyTypes" :key="item.name" :label="item.name" :value="item.name" /></el-select></el-form-item><el-form-item label="优先级"><el-input v-model.number="form.priority" type="number" /></el-form-item><el-form-item label="目标功率"><el-input v-model="form.power" /></el-form-item><el-form-item label="SOC目标"><el-input v-model="form.targetSoc" /></el-form-item><el-form-item label="调度计划"><el-input v-model="form.schedule" /></el-form-item><el-form-item label="触发条件"><el-input v-model="form.trigger" /></el-form-item></el-form><template #footer><el-button @click="modal = false">取消</el-button><el-button type="primary" @click="saveStrategy">保存</el-button></template></el-dialog>
  </div>
</template>
