<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import type { EChartsOption } from 'echarts'
import ChartBox from '@/components/ChartBox.vue'
import KpiCard from '@/components/KpiCard.vue'
import PowerFlow from '@/components/PowerFlow.vue'
import { useEmsStore } from '@/stores/ems'

const props = defineProps<{ section: 'overview' | 'revenue' | 'energy' | 'tariff' | 'demand' }>()
const store = useEmsStore()
const tariffModal = ref(false)
const tariffView = ref<'table' | 'chart'>('table')
const energyRange = ref<'日' | '月' | '年'>('日')
const energyDate = ref('2026-07-15')
const keyword = ref('')
const pageSize = ref(8)
const currentPage = ref(1)
const tariffForm = reactive({ period: '', price: 0 })
const selectedStationId = ref(store.station.id)
const title = computed(() => ({ overview: '运营总览', revenue: '收益明细', energy: '充放电统计', tariff: '电价管理', demand: '需量管理' }[props.section]))
const subtitle = computed(() => ({ overview: '电站收益、能量、效率与功率流向', revenue: '收益分项与趋势分析', energy: '充放电历史查询与效率分析', tariff: '分时电价策略维护', demand: '十五分钟需量曲线与削峰效果' }[props.section]))
const currentTariffs = computed(() => store.getStationTariffs(selectedStationId.value))
watch(selectedStationId, () => { currentPage.value = 1; keyword.value = '' })
const openTariff = (item: typeof store.tariffs[number]) => { Object.assign(tariffForm, item); tariffModal.value = true }
const saveTariff = () => { store.updateTariff(tariffForm.period, Number(tariffForm.price), selectedStationId.value); tariffModal.value = false }
const powerOption = computed<EChartsOption>(() => ({ tooltip: { trigger: 'axis' }, legend: { top: 8 }, grid: { left: 60, right: 24, top: 58, bottom: 42 }, xAxis: { type: 'category', name: '时间', data: ['00', '04', '08', '12', '16', '20', '24'] }, yAxis: { type: 'value', name: '功率(kW)' }, series: [{ name: '负荷', type: 'line', smooth: true, data: [820, 760, 1680, store.snapshot.loadPower, 1860, 2280, 920] }, { name: '光伏', type: 'line', smooth: true, data: [0, 0, 180, store.snapshot.pvPower, 360, 0, 0] }, { name: '储能', type: 'bar', data: [-520, -480, 0, store.snapshot.storagePower, 0, 680, -430] }] }))
const revenueOption = computed<EChartsOption>(() => ({ tooltip: { trigger: 'axis' }, legend: { top: 10 }, grid: { left: 64, right: 24, top: 78, bottom: 46 }, xAxis: { type: 'category', name: '日期', data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'] }, yAxis: { type: 'value', name: '收益(元)' }, series: [{ name: '削峰填谷', type: 'bar', stack: '收益', data: [3260, 3480, 3860, store.snapshot.todayRevenue, 3980, 2760, 2880] }, { name: '需量管理', type: 'bar', stack: '收益', data: [820, 760, 910, 960, 880, 520, 560] }, { name: '调频收益', type: 'line', data: [260, 320, 300, 360, 340, 280, 310] }] }))
const overviewBenefitOption = computed<EChartsOption>(() => ({ tooltip: { trigger: 'axis' }, legend: { top: 8 }, grid: { left: 62, right: 14, bottom: 46, top: 70 }, xAxis: { type: 'category', name: '收益类型', data: ['削峰填谷', '需量收益', '调频收益', 'CO₂减排'] }, yAxis: { type: 'value', name: '金额/减排' }, series: [{ name: '收益指标', type: 'bar', barWidth: 28, data: [{ value: store.snapshot.todayRevenue, itemStyle: { color: '#409eff' } }, { value: 820.45, itemStyle: { color: '#67c23a' } }, { value: 310.2, itemStyle: { color: '#e6a23c' } }, { value: 486.32, itemStyle: { color: '#909399' } }] }] }))
const energyOption = computed<EChartsOption>(() => ({ tooltip: { trigger: 'item' }, legend: { bottom: 0 }, series: [{ name: '能量分布', type: 'pie', radius: ['45%', '70%'], center: ['50%', '45%'], data: [{ name: '谷时充电', value: store.snapshot.chargeEnergy }, { name: '峰时放电', value: store.snapshot.dischargeEnergy }, { name: '平时待机', value: 420 }] }] }))
const energyHistoryOption = computed<EChartsOption>(() => { const labels = energyRange.value === '日' ? ['00','04','08','12','16','20','24'] : energyRange.value === '月' ? ['1日','5日','10日','15日','20日','25日','30日'] : ['1月','3月','5月','7月','9月','11月','12月']; return { tooltip: { trigger: 'axis' }, legend: { top: 8 }, grid: { left: 62, right: 24, top: 62, bottom: 42 }, xAxis: { type: 'category', name: '时间', data: labels }, yAxis: { type: 'value', name: '电量/效率' }, series: [{ name: '充电量', type: 'bar', data: [120, 168, 210, store.snapshot.chargeEnergy, 188, 162, 132] }, { name: '放电量', type: 'bar', data: [116, 152, 196, store.snapshot.dischargeEnergy, 174, 151, 125] }, { name: '效率', type: 'line', yAxisIndex: 0, data: [90.6, 91.2, 91.5, 91.72, 91.4, 90.9, 91.1] }] } })
const tariffOption = computed<EChartsOption>(() => ({ tooltip: { trigger: 'axis' }, legend: { top: 8 }, grid: { left: 62, right: 20, top: 62, bottom: 48 }, xAxis: { type: 'category', name: '时段', data: currentTariffs.value.map((item) => item.period) }, yAxis: { type: 'value', name: '电价(元/kWh)' }, series: [{ name: '电价', type: 'line', step: 'middle', areaStyle: {}, data: currentTariffs.value.map((item) => item.price) }] }))
const revenueRows = computed(() => [{ name: '削峰填谷', today: '3,260.18 元', month: '62,186.34 元', year: '468,320.88 元', desc: '峰放谷充价差' }, { name: '需量管理', today: '820.45 元', month: '18,216.00 元', year: '132,480.00 元', desc: '削减最大需量' }, { name: '调频收益', today: '310.20 元', month: '6,018.04 元', year: '42,117.84 元', desc: '响应调度指令' }])
const filteredRevenueRows = computed(() => revenueRows.value.filter((item) => !keyword.value || `${item.name}${item.desc}`.includes(keyword.value)))
const revenuePageRows = computed(() => filteredRevenueRows.value.slice((currentPage.value - 1) * pageSize.value, currentPage.value * pageSize.value))
const filteredTariffs = computed(() => currentTariffs.value.filter((item) => !keyword.value || `${item.period}${item.type}`.includes(keyword.value)))
const tariffRows = computed(() => filteredTariffs.value.slice((currentPage.value - 1) * pageSize.value, currentPage.value * pageSize.value))
const energyRows = computed(() => ['00:00-04:00','04:00-08:00','08:00-12:00','12:00-16:00','16:00-20:00','20:00-24:00'].map((period, index) => ({ period, charge: [126.4, 198.2, 42.8, 0, 18.6, 156.4][index], discharge: [0, 0, 185.6, 226.4, 246.8, 86.2][index], efficiency: [91.2, 91.6, 92.1, 91.8, 91.4, 90.9][index] })))
const energyPageRows = computed(() => energyRows.value.slice((currentPage.value - 1) * pageSize.value, currentPage.value * pageSize.value))
const efficiency = computed(() => Math.min(99.99, store.snapshot.chargeEnergy ? (store.snapshot.dischargeEnergy / store.snapshot.chargeEnergy * 100) : 0).toFixed(2))
</script>

<template>
  <div class="page-grid tob-page">
    <template v-if="section === 'overview'">
      <KpiCard label="今日净收益" :value="store.format.yuan(store.snapshot.todayRevenue)" hint="实时累计" tone="green" />
      <KpiCard label="SOC" :value="store.format.pct(store.snapshot.soc)" hint="安全运行区间" tone="blue" />
      <KpiCard label="充电电量" :value="store.format.kwh(store.snapshot.chargeEnergy)" hint="当日累计" tone="green" />
      <KpiCard label="综合效率" value="91.72%" hint="循环效率" tone="orange" />
      <section class="data-section span-8"><PowerFlow /></section>
      <section class="data-section span-4"><ChartBox :option="overviewBenefitOption" :updated-at="store.snapshot.timestamp" /></section>
    </template>
    <section v-else-if="section === 'revenue'" class="data-section span-12"><ChartBox :option="revenueOption" :updated-at="store.snapshot.timestamp" /><div class="query-bar"><el-input v-model="keyword" clearable placeholder="收益项 / 说明" /><el-button type="primary">查询</el-button><el-button @click="keyword = ''">重置</el-button></div><el-table :data="revenuePageRows" stripe><el-table-column prop="name" label="收益项" /><el-table-column prop="today" label="今日" /><el-table-column prop="month" label="本月" /><el-table-column prop="year" label="本年" /><el-table-column prop="desc" label="说明" /></el-table><div class="pager-row"><el-pagination v-model:current-page="currentPage" v-model:page-size="pageSize" :total="filteredRevenueRows.length" layout="total, sizes, prev, pager, next, jumper" /></div></section>
    <section v-else-if="section === 'energy'" class="data-section span-12"><div class="date-tools"><el-radio-group v-model="energyRange"><el-radio-button label="日" /><el-radio-button label="月" /><el-radio-button label="年" /></el-radio-group><el-date-picker v-model="energyDate" :type="energyRange === '日' ? 'date' : energyRange === '月' ? 'month' : 'year'" value-format="YYYY-MM-DD" /><el-tag type="success">充放电效率 {{ efficiency }}%</el-tag></div><div class="split"><ChartBox :option="energyOption" :updated-at="store.snapshot.timestamp" /><ChartBox :option="energyHistoryOption" :updated-at="store.snapshot.timestamp" /></div><div class="query-bar"><el-input v-model="keyword" clearable placeholder="历史时段" /><el-button type="primary">查询</el-button><el-button @click="keyword = ''">重置</el-button></div><el-table :data="energyPageRows" stripe><el-table-column prop="period" label="时段" /><el-table-column label="充电量"><template #default="{ row }">{{ row.charge.toFixed(2) }} kWh</template></el-table-column><el-table-column label="放电量"><template #default="{ row }">{{ row.discharge.toFixed(2) }} kWh</template></el-table-column><el-table-column label="效率"><template #default="{ row }">{{ Math.min(99.99, row.efficiency).toFixed(2) }}%</template></el-table-column></el-table><div class="pager-row"><el-pagination v-model:current-page="currentPage" v-model:page-size="pageSize" :total="energyRows.length" layout="total, sizes, prev, pager, next, jumper" /></div></section>
    <section v-else-if="section === 'tariff'" class="data-section span-12"><div class="date-tools"><el-select v-model="selectedStationId" style="width: 260px"><el-option v-for="station in store.stations" :key="station.id" :label="station.name" :value="station.id" /></el-select><el-tag type="primary">当前电价配置随电站联动</el-tag></div><el-tabs v-model="tariffView" class="tariff-tabs"><el-tab-pane label="表格配置" name="table" /><el-tab-pane label="电价曲线" name="chart" /></el-tabs><template v-if="tariffView === 'table'"><div class="query-bar"><el-input v-model="keyword" clearable placeholder="时段 / 类型" /><el-button type="primary">查询</el-button><el-button @click="keyword = ''">重置</el-button></div><el-table :data="tariffRows" stripe height="500"><el-table-column prop="period" label="时段" /><el-table-column prop="type" label="类型"><template #default="{ row }"><el-tag :type="row.type === '峰' ? 'danger' : row.type === '谷' ? 'success' : 'warning'">{{ row.type }}</el-tag></template></el-table-column><el-table-column label="电价"><template #default="{ row }">{{ row.price.toFixed(2) }} 元/kWh</template></el-table-column><el-table-column label="适用日期"><template #default>工作日、节假日独立配置</template></el-table-column><el-table-column label="操作"><template #default="{ row }"><el-button link type="primary" @click="openTariff(row)">编辑</el-button></template></el-table-column></el-table><div class="pager-row"><el-pagination v-model:current-page="currentPage" v-model:page-size="pageSize" :total="filteredTariffs.length" layout="total, sizes, prev, pager, next, jumper" /></div></template><ChartBox v-else :option="tariffOption" :updated-at="store.snapshot.timestamp" /></section>
    <section v-else class="data-section span-12 demand-full"><ChartBox :option="powerOption" :updated-at="store.snapshot.timestamp" /><div class="detail-grid"><article><label>无储能最大需量</label><strong>2,486.0 kW</strong></article><article><label>储能削峰后需量</label><strong>1,934.0 kW</strong></article><article><label>需量电费节省</label><strong>18,216.00 元</strong></article></div></section>
    <el-dialog v-model="tariffModal" destroy-on-close class="ems-dialog" title="电价维护" width="520px"><el-form :model="tariffForm" label-width="80px"><el-form-item label="时段"><el-input v-model="tariffForm.period" disabled /></el-form-item><el-form-item label="电价"><el-input v-model.number="tariffForm.price" type="number" /></el-form-item></el-form><template #footer><el-button @click="tariffModal = false">取消</el-button><el-button type="primary" @click="saveTariff">保存</el-button></template></el-dialog>
  </div>
</template>
